"use client"

import { useEffect, useState } from "react"

type Post = {
  slug: string
  date: string
  title: string
  tag: string
  body: React.ReactNode
}

const posts: Post[] = [
  { slug: "complete-wellness-workspace", date: "01 Jul 2025", title: "Creating Your Complete Wellness Workspace (Without the Corporate Nonsense)", tag: "Integrated Membership", body: <><p>You&apos;ve tried the fancy coworking spaces with ping-pong tables and kombucha on tap. You&apos;ve endured corporate wellness programmes with mandatory mindfulness sessions and step-counting competitions. You may even have built the perfect home office with ergonomic everything and motivational quotes.</p><p>But real wellness at work isn&apos;t about perks or programmes. It&apos;s about creating an environment where professional life and personal wellbeing support each other, rather than competing for attention.</p><h2>Stop performing wellness</h2><p>Most workplace wellness initiatives are wellness theatre: they look good on paper but leave the real sources of stress untouched. A complete workspace should make focused work, recovery, community and meaningful growth easier to access every day.</p><h2>What an integrated membership makes possible</h2><ul><li>A calm, considered place to focus and do deep work</li><li>Flexible workspace that supports different rhythms and working styles</li><li>Wellbeing practices built into the working day, not bolted on as an afterthought</li><li>Genuine community, connection and conversations that move ideas forward</li><li>Practical support for sustainable performance without the corporate nonsense</li></ul><h2>The complete wellness workspace</h2><p>The best workspace is not simply a desk. It is an ecosystem: a place to work, reset, meet people, learn and build a life around work that feels coherent. That is the value of an integrated membership — one thoughtful environment supporting the whole person.</p><blockquote>Wellness is not a perk. It is the condition that makes good work sustainable.</blockquote></> },
  { slug: "wealth-creation", date: "Ongoing", title: "Deconstructing my idea of Wealth Creation", tag: "Finance", body: <><h2>Fundamentals for a Wealth Creation Mindset</h2><p>Income is a flow. Wealth is a stock — the accumulation of assets that generate value independently of your labour.</p><h2>Building Types of Wealth</h2><h3>Entrepreneurial — creative as a child of God</h3><p>There is something deeply human about building. The instinct to create, solve, and bring something new into existence is a meaningful form of value creation.</p><blockquote>Profit can be a liability. The reputation of your company and maintaining that is pivotal.</blockquote><h2>Establish Values</h2><p>Wealth without values is extraction without purpose. Scale should amplify what you stand for, not replace it.</p></> },
  { slug: "ux-2060", date: "18 Mar 2026", title: "Future Trends for UX/UI Designers: Staying Relevant to 2060", tag: "UX", body: <><p>Where do UX/UI designers need to pivot in order to stay relevant in 2060? Buzz words change quickly, but the need to understand people, systems, and the physical world will remain.</p><blockquote>I always said I was going to be an inventor. I now think it&apos;s closer to being an entrepreneur than a mechanical engineer.</blockquote><h2>Two possible futures for UX</h2><p>UI design may require the same 3D skills as industrial design, putting interfaces into VR using game engines. Or UX may become a cyber-physical discipline, bridging tangible and graphical interaction.</p><h2>The move to business analysts for scrum mastery</h2><p>It is not enough to be aware of UX. Designers who understand the whole system — not just the screen — will be best placed to shape what comes next.</p></> },
  { slug: "agile-ux", date: "27 Oct 2024", title: "Building Integrated AgilePM — User eXperiences", tag: "Agile", body: <><p>Agile project management and UX design have long been treated as adjacent disciplines. The more interesting question is what happens when you integrate them from the ground up as a shared culture.</p><h2>The marketing strategy</h2><p>Clients and partners on one side. AgilePM on the other. The model only works when both sides can see the same horizon.</p><ul><li>Your solution</li><li>The problem you are fixing</li><li>Your alternatives</li><li>A genuine understanding of your audience</li></ul><blockquote>Real agility is removing unnecessary bureaucracy so talented people can get things done.</blockquote></> },
  { slug: "accessibility", date: "03 Mar 2025", title: "eBay creates an accessibility tool for designers and engineers", tag: "Accessibility", body: <><p>eBay&apos;s accessibility tool for designers and engineers is a notable shift — moving accessibility from a compliance checklist into the design and development workflow.</p><h2>Why it matters</h2><p>When designers and engineers share the same vocabulary, tool, and output, there are fewer translation errors and fewer “that&apos;s a dev problem” moments.</p><h2>The broader implication</h2><p>Accessibility cannot be a late-stage audit. It has to be a design material, as early and as fundamental as colour or type.</p></> },
  { slug: "marshall", date: "26 Jul 2024", title: "My experience working at Marshall Amplification PLC", tag: "Career", body: <><p>Marshall Amplification was my first professional encounter with design at the intersection of heritage and technology.</p><h2>What I took away</h2><p>Working inside a company whose product is iconic taught me the weight of making things that last — and the relationship between brand, engineering, and the person who holds the product.</p></> },
  { slug: "safe", date: "24 Mar 2025", title: "SAFe Scalable Agile Framework Updates", tag: "Agile", body: <><p>SAFe continues to evolve around a central tension: structure can make agile enterprise-ready, but too much structure can remove its adaptability.</p><h2>The real question</h2><p>The useful exercise is developing the judgment to know which parts of a framework serve your context and which can be left on the shelf.</p><blockquote>A framework is a starting point. The discipline is knowing when to follow it and when to set it aside.</blockquote></> },
  { slug: "lessons-industry", date: "2017", title: "Lessons from Industry", tag: "Career", body: <><p>My apprenticeship taught me responsive design, software engineering, and the pace of the real world. Clients do not wait for you to feel ready.</p><h2>Invoicing £150 for a trial week</h2><p>Knowing what your time is worth before anyone else does is an act of professionalism.</p></> },
  { slug: "dont-build-alone", date: "Reflections", title: "Don&apos;t Build Alone", tag: "Leadership", body: <><blockquote>Even the most visionary leaders need counsel. Seeking advice isn&apos;t weakness — it&apos;s wisdom.</blockquote><p>The mythology of the lone founder is seductive and dangerous. Build a room where people will tell you when you are wrong, especially when you are sure you are right.</p></> },
  { slug: "leadership-management", date: "Reflections", title: "Leadership vs. Management", tag: "Leadership", body: <><p>Framing an assignment is a skill. Giving the why and creating a sense of importance is the core of effective leadership.</p><h2>The distinction that matters</h2><p>Management is stewardship of existing systems. Leadership points somewhere new and persuades people the journey is worth it.</p></> },
  { slug: "routes-to-finance", date: "Oct 2024", title: "Routes to Finance", tag: "Finance", body: <><p>Since being laid off, I have been looking for alternative sources of finance — from friends and family, to co-founders, specialists, and a co-operative structure.</p><h2>Co-operative structure</h2><p>Giving all partners ownership from the beginning creates a clean, fair exit path and aligns responsibility with the mission.</p></> },
  { slug: "social-media", date: "2025", title: "Why is it so hard for large organisations to just… post something?", tag: "Leadership", body: <><p>Getting one LinkedIn post live can involve marketing, brand, comms, legal, compliance, leadership, and regional teams. By the time everyone has had their say, the event has passed.</p><blockquote>The bigger problem is what approval processes do to people.</blockquote><h2>The fix</h2><p>Give a small team clear ownership, guardrails, and the authority to run with it. Governance and agency can coexist.</p></> },
  { slug: "building-team", date: "Oct 2024", title: "Building the Team", tag: "Leadership", body: <><p>Creating a culture means building before you scale. The first community assigned to you is family, followed by the wider communities that support meaningful work.</p><h2>The right co-founders</h2><p>Bring values and align the mission before scale forces the question.</p></> },
  { slug: "mergers", date: "2025", title: "Mergers, Acquisitions & Partnerships", tag: "Finance", body: <><p>Do you need advice on the technology you are acquiring, or help finding the greater potential in things?</p><h2>Technical due diligence</h2><p>Understanding technical debt means communicating across finance, software development, and electronics engineering — from cloud architecture down to embedded systems.</p><h2>What to look for</h2><ul><li>Early, undervalued start-ups</li><li>Young talent and pre-seed investment</li><li>Essential business functions</li><li>Current and projected turnover</li></ul></> },
]

export function BlogPage() {
  const [selected, setSelected] = useState<string | null>(null)
  const post = posts.find((item) => item.slug === selected)

  useEffect(() => {
    const slug = window.location.hash.slice(1)
    if (posts.some((item) => item.slug === slug)) setSelected(slug)
    const onHashChange = () => setSelected(window.location.hash.slice(1) || null)
    window.addEventListener("hashchange", onHashChange)
    return () => window.removeEventListener("hashchange", onHashChange)
  }, [])

  const openPost = (slug: string) => {
    setSelected(slug)
    window.history.pushState({ slug }, "", `/blog#${slug}`)
    window.scrollTo({ top: 0, behavior: "smooth" })
  }

  const showIndex = () => {
    setSelected(null)
    window.history.pushState({}, "", "/blog")
    window.scrollTo({ top: 0, behavior: "smooth" })
  }

  return <main className="min-h-screen bg-background text-foreground"><nav className="sticky top-0 z-50 border-b border-border bg-background/95 px-6"><div className="mx-auto flex h-14 max-w-6xl items-center justify-between"><button type="button" onClick={showIndex} className="font-serif text-xl text-[#c4622d]">Riaz Virani</button><div className="flex gap-7 font-mono text-[10px] uppercase tracking-[0.18em] text-muted-foreground"><a href="/" className="hover:text-foreground">Home</a><a href="/blog" className="text-foreground">Writing</a><a href="/#contact" className="hover:text-foreground">About</a></div></div></nav>{post ? <article className="mx-auto max-w-6xl px-6"><button type="button" onClick={showIndex} className="py-6 font-mono text-[10px] uppercase tracking-[0.15em] text-muted-foreground hover:text-foreground">← All posts</button><header className="max-w-[680px] border-b border-border pb-10 pt-4"><div className="mb-5 flex items-center gap-3"><span className="rounded-full border border-border px-3 py-1 font-mono text-[10px] uppercase tracking-wider text-muted-foreground">{post.tag}</span><span className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground">{post.date}</span></div><h1 className="font-serif text-4xl leading-[1.08] tracking-tight md:text-5xl">{post.title}</h1></header><div className="prose-blog max-w-[680px] py-11">{post.body}</div></article> : <><header className="mx-auto max-w-6xl border-b border-border px-6 pb-12 pt-20"><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-[#4b7771]">Writing & research</p><h1 className="mt-4 max-w-xl font-serif text-5xl leading-none tracking-tight md:text-6xl">Ideas for building with <em className="text-[#4b7771]">purpose.</em></h1><p className="mt-5 max-w-xl text-sm leading-relaxed text-muted-foreground">Essays on UX, connected products, accessibility, agile delivery, leadership and creating lasting value.</p></header><ul className="mx-auto mt-12 max-w-6xl border-t border-border px-6">{posts.map((item) => <li key={item.slug}><button type="button" onClick={() => openPost(item.slug)} className="group flex w-full flex-col gap-2 border-b border-border py-6 text-left transition-colors hover:bg-secondary/60 md:flex-row md:items-center md:gap-8 md:px-2"><span className="font-mono text-xs tracking-wider text-muted-foreground md:w-28 md:shrink-0">{item.date}</span><span className="flex-1 font-serif text-xl tracking-tight md:text-2xl">{item.title}</span><span className="flex items-center gap-4 md:shrink-0"><span className="rounded-full border border-border px-3 py-1 font-mono text-[10px] uppercase tracking-wider text-muted-foreground">{item.tag}</span><span className="font-mono transition-transform group-hover:translate-x-1">→</span></span></button></li>)}</ul></>}<footer className="mt-20 border-t border-border px-6 py-8 text-center font-mono text-[10px] uppercase tracking-wider text-muted-foreground">ServantLeaders · Haven Carty · All rights reserved</footer></main>
}
